### ISSUE TITLE
sshterm stopped connecting to servers

### ISSUE THREAD

**Issue by walkero-gr** [salass00/sshterm#1]
Since a couple of days ago, sshterm v1.8 stopped connecting to any of the servers I use it for. When I try to connect, the password window appears and after I fill up my password, I get the error message "Authentication by password failed". No matter if I copy and paste the password, or type it, it fails 9 out of 10 times.

Is there something that could make it change the way it worked?

**Comment by walkero-gr** [comment]
@salass00 I did an investigation on the problem and seems that:
1. sshterm works fine if I give the password as an argument, and not through the Password Requester
2. I tried to printf buffer before the strdup at https://github.com/salass00/sshterm/blob/master/src/main.c#L113 and what I got is the password I inserted at the requester and the the character 'n' and then memory trash for the rest of 256 characters, ie. 12345n[repeating trash here]

I believe the buffer and wherever the password is stored should be cleared from the memory as soon as it is used, otherwise it might be a security issue there. 

Hope I helped tracking down the bug.
Tested on X5000 with latest AmigaOS 4.1 FE upd 2.

**Comment by salass00** [comment]
You mean there is an 'n' character where the null-terminator should be? That is very odd and I am unable to reproduce it here on my Sam460 (I use public key authentication but the code for the password/passphrase requester is the same).

**Comment by walkero-gr** [comment]
Yes, the n character should be the null terminator. I will try to see if this is a problem that comes from somewhere else, but I can't relate yet with anything. I will continue the investigation. If in any way you have something in mind that could influence it, please tell me so.

**Comment by salass00** [comment]
Looks like I'm able to reproduce the bug now on my Tabor system with the latest development version of graphics.library now. Likely it is some kind of race condition in string.gadget (and maybe requester.class) as changing the speed of some graphics operations seems to trigger it. I will see if I can find the cause and fix it.

**Comment by walkero-gr** [comment]
Thank you so much for that.

**Comment by salass00** [comment]
This issue should be fixed in the latest beta string.gadget.
