### ISSUE TITLE
Crash when copying without anything marked

### ISSUE THREAD

**Issue by jaokim** [salass00/sshterm#2]
When copying without any text marked, SSHTerm crashes.

To reproduce:
1. Connect to a server with SSHTerm
2. Either press Amiga-C, or choose Copy from the menu.
Expected result: nothing
Actual result: a crash

See http://crashlog.os4depot.net/cl426 for crash log.
SSHTerm version 1.8.

**Comment by salass00** [comment]
Thanks for reporting. It should be fixed now.
